### ISSUE TITLE
emacsclient as part of 27.1-1 installation not in documented location.

### ISSUE THREAD

**Issue by gmc444-b** [caldwell/build-emacs#100]
I recently installed 27.1-1 and started through the tips here: https://emacsformacosx.com/tips

When trying to set up emacsclient, it wasn't present in the documented location. I did find it here: 

/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/emacsclient

**Comment by ssunday** [comment]
Not quite related but I was able to solve my problem from your comment.

I was having issues with `emacsclient` throwing: `Error: server did not start correctly` when trying to launch it after upgrading from 27.1 to 27.2 on M1 Macs. The fix was setting my `emacsclient` location to `/Applications/Emacs.app/Contents/MacOS/bin-arm64-11_2/emacsclient` This would be good to get documented in https://emacsformacosx.com/tips maybe.

**Comment by caldwell** [comment]
That was broken on a specific build and should be fixed now.
