### ISSUE TITLE
File permissions [Switch back to HFS+ disk images]

### ISSUE THREAD

**Issue by tfeb** [caldwell/build-emacs#110]
I am not sure if this is the right place to report this.

It looks to me as if the permissions on the 27.2.2 DMG are 777 for everything, so rwxrwxrwx.  This is probably bad.

However, I used an emacs from this DMG for ages on 10.14: it wasn't until macOS 11 that something complained at me.  So this might actually be some 11.x change?

What I did to resolve it is juct `chmod -R go-w .../Emacs.app` which works fine.

**Comment by caldwell** [comment]
It's not great. Unfortunately it's like that because there is a bug in Apple's dmg creation tools on M1 hardware—trying to create HFS+ disk images just fails. I've reported it to Apple, but I don't know if/when they will fix it.

APFS images can be created, but unfortunately I'm targeting old MacOS versions that don't support APFS. So I have to fall back to some other disk images that are supported on old machines. Currently the only ones that are old enough and actually work are UFS and FAT. Neither of which store permissions correctly (IIRC). I don't remember which one I ended up choosing, but it was the one that made smaller images.

**Comment by caldwell** [comment]
I looks like Apple fixed this In Monterey (or an update, not exactly sure when). The builds are now using HFS again. [The 2022-04-05_14-51-13 nightly version](https://emacsformacosx.com/emacs-builds/Emacs-2022-04-05_14-51-13-575c3beb4c001687ce7a4581de005a16d6f2e081-universal.dmg) is the first one back on HFS+.
