### ISSUE TITLE
Warning of libexec directory missing

### ISSUE THREAD

**Issue by mat5n** [caldwell/build-emacs#141]
When I start Emacs 29.4, the following warning appears in `*Messages*`:

```
Warning: arch-dependent data dir Contents/MacOS/libexec/: No such file or directory
```

The warning goes away if I symlink `libexec` to `libexec-<arch>`. Creating an empty directory by that name works too.

Version 29.2 didn't have this problem, but then its `Contents/MacOS` did contain `libexec` which was a symlink pointing to `libexec-x86_64-10_11`.

Everything seems to work fine even with the warning so it's mostly a cosmetic thing.

**Comment by dieggsy** [comment]
I will add that this does affect some functionality, namely anything depending on:

- `libexec/hexl` (hexl-mode)
- `libexec/movemail` (not sure what uses this)
- `libexec/rcs2log` (not sure what uses this)

**Comment by caldwell** [comment]
Thanks for catching that.

It happened because that bin directory was a hardcoded configuration that I forgot to update when I switched the minimum macOS to 10.12 recently. This annoyed me, so [I made it automatic](https://github.com/caldwell/build-emacs/commit/76a76955a943806994cc698b0a12ee2eab71e6e3). The patch also makes the binaries in them universal and not just x86_64—I'm not sure any of them being arm native will make a substantial difference anywhere, but it certainly can't hurt

I just rebuilt the release Emacs (29.4-1) which should be up on the site now with good bin and libexec dirs.
