### ISSUE TITLE
Default load-path includes non-existent directories, omits 24.4 lisp files.

### ISSUE THREAD

**Issue by mejohnsn** [caldwell/build-emacs#36]
The default load-path upon installing on a Macbook Pro running OS X 10.9.5 includes many subdirectories under /User/build, which does not exist on this system. In particular, one of these has the only reference to an emacs/24.4/ subdirectory, the site-lisp one.

I have not searched the whole list of load-list, but I do know that recentf-mode.elc, *which came in /usr/share/emacs/22.1/lisp in the version of emacs that comes with OS X), is not being loaded: I get an error message when I require either this or protobuf-mode from my .emacs file while loading Emacs (instead of the /usr/bin/emacs that came with the system).

**Comment by caldwell** [comment]
> 1) why all these non-existent directories

This has to do with the way Emacs packages itself. It always hardcodes the "prefix" in the `load-path`. Under linux this would usually be '/usr/share/emacs', but when building the Mac .app bundle, the Makefile abuses the prefix so that it installs everything in an Emacs.app in its source directory. 

> 2) since /User/build/.../emacs/24.4/site-lisp does not exist, where are we supposed to put emacs lisp files for our site customization?

That's a good question. It appears that is an oversight on Emacs's part. I'm going to file a bug with Emacs with a patch that changes the paths in question 1 to `/Library/emacs/...` which should solve both your issues. We'll see what they say…

The bug w/patch I reported is [here](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19850).

**Comment by caldwell** [comment]
Jan D. fixed the main path bug, but didn't want to make /Library a default site-lisp path for some reason. That's ok because it's configurable: 86e4c4d3bb now sets it to:

     /Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp

This is in the 24.5 release.
