### ISSUE TITLE
environment variables lost

### ISSUE THREAD

**Issue by russellsimpkins-nyt** [caldwell/build-emacs#51]
I'm on using this version of your emacs:

GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-20 on builder10-9.porkrind.org

When I start emacs, I loose the environment variables set in .bashrc and .bash_profile

Is this by design or did I screw something up. I discovered this by placing a binary in a non-standard location and then attempted to run the compile function. In particular, in doing development with the go language, the binary is in /usr/local/go/bin and it expects a default GOPATH variable set. Running items from the shell within emacs works because I added a init_bash.sh script in .emacs.d, but that fix doesn't help subprocesses.

If I click on the packaged app icon, the GOPATH is not set and my PATH doesn't include /usr/local/go/bin - If i manually run one of the executables in the MacOS folder under the Emacs package, the path is set correctly, but a new terminal window is left open.

**Comment by caldwell** [comment]
I assume you are starting it by clicking in the Dock, or launching from Finder. In this case, Apple does not pass environment variables on from `.bashrc` (as it is not run as part of the log-in process). There used to be ways to get this to work automatically, but Apple has been systematically removing them. The only way I know how to make it work is to run `launchctl setenv` which will set the environment inside launchd, so that all subsequently run programs will get them. This also means that after you run `launchctl setenv` you need to `killall Dock` and `killall Finder` so that the relaunch with the updated variables. It's also not persistent, so you have to do this on every reboot. This is a pain.

Currently, I put this in my .bashrc:

    for e in CPATH CVS_RSH EDITOR EMAIL GL_ENABLE_DEBUG_ATTACH HOSTFILE LIBRARY_PATH LOGNAME MANPATH PAGER PATH PERL5LIB PKG_CONFIG_PATH VISUAL; do
        eval launchctl setenv "\"\$e\"" "\"\${$e}\""
    done

That forwards a list of variables I want in all programs launched from finder. There's some obsolete stuff in there (I haven't used CVS in years), so if you use it you should prune those down to things you care about (like `GOPATH` and maybe `PATH`).

This updates launchctl every time you open a new tab in terminal. So on boot up, I launch terminal and then `killall Dock` before launching Emacs. And every time it feels like a massive kludge.

Another thing you can do is to launch Emacs from the command line:

    /Applications/Emacs.app/Contents/MacOS/Emacs

That will run Emacs from the shell, and so it will inherit the shell's environment—since your shell runs `.bashrc` automatically, it should have all your GOPATH and PATH set up nicely.

Those are the only 2 ways to fix this that I currently know about. Also take a look at #32, which proposes a fix for this in a nicer way. I wasn't quite happy with the way it was implemented, but I think given the current state of environment variables in the MacOS, it has become important.

**Comment by russellsimpkins-nyt** [comment]
Thanks for getting back to me. I decided to use Automator and used the following

```
if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi
/usr/bin/nohup /Applications/Emacs.app/Contents/MacOS/Emacs >/dev/null 2>&1 &
```
This seems to work well. I got the idea from

http://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items

**Comment by lunaryorn** [comment]
Just FYI, there's also https://github.com/purcell/exec-path-from-shell which can import environment variables into a running Emacs instance.
