### ISSUE TITLE
srgb?

### ISSUE THREAD

**Issue by mkleehammer** [caldwell/build-emacs#56]
According to this article, the "--srgb" flag is needed for proper rendering: http://emacsredux.com/blog/2013/08/21/color-themes-redux/

I haven't looked through the build scripts but thought I'd point it out for someone who is more familiar with them.

**Comment by caldwell** [comment]
The `--srgb` flag shown was for homebrew, which used to apply a patch the Emacs code for srgb support. That patch has since been moved into the main Emacs codebase and the patch is not needed (and if you look at [the latest homebrew emacs.rb formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb), the flag doesn't exist any more).

The article is old and outdated.
