### ISSUE TITLE
How to run emacs from command line?

### ISSUE THREAD

**Issue by chetstone** [caldwell/build-emacs#57]
I installed emacs 25.1.1 using `brew cask install emacs`. All went well (I can run it by launching from the finder) until I tried to create a symlink to run emacs from the command line. I tried

```
ln -s /Applications/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs
```
and when I run it I get a popup that says `This application will not run on your computer. Sorry!`

I discovered that when run from the finder it actually uses `Emacs-x86_64-10_9` (I'm on Yosemite) so I tried 
```
ln -s /Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_9 /usr/local/bin/emacs
```
and I get:
```
Warning: arch-dependent data dir '/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/MacOS/libexec/': No such file or directory
Warning: arch-independent data dir '/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/Resources/etc/': No such file or directory
Warning: Lisp directory '/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/Resources/lisp': No such file or directory
Error: charsets directory not found:
/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/Resources/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
```

What is the secret?

thanks

**Comment by caldwell** [comment]
Using an alias should work: `alias emacs=/Application/Emacs.app/Contents/MacOS/Emacs`. Of course that only works if you are typing emacs into a shell. If you want other programs to be able to launch Emacs (maybe it's in your `EDITOR` env var, for instance), you need to do something else. I use a little stub shell script (as described [here](https://emacsformacos.com/tips)):

```bash
#!/bin/sh
/Applications/Emacs.app/Contents/MacOS/Emacs "$@"
```

I'm not going to close this bug though, because I think using a symlink *should* work. The launcher script should be able to detect that and act appropriately.

**Comment by chetstone** [comment]
Thanks! That works...
