### ISSUE TITLE
Usage Issue

### ISSUE THREAD

**Issue by ghost** [caldwell/build-emacs#64]
Hi,

I was trying to build latest emacs for power pc using your scripts on a mac mini g4. 
I have first tried to download the source: 

./fetch-emacs-from-ftp ftp://ftp.gnu.org/pub/gnu/emacs/emacs-25.2.tar.xz                 master

and get this output:

./fetch-emacs-from-ftp:18: warning: parenthesize argument(s) for future version
./fetch-emacs-from-ftp:40:in `popen': can't convert Array into String (TypeError)
	from ./fetch-emacs-from-ftp:40

Also get errors when executing the whole line the example:

./fetch-emacs-from-ftp -v ftp://ftp.gnu.org/pub/gnu/emacs
+ curl --continue-at - --silent -O ftp://ftp.gnu.org/pub/gnu/emacs/emacs-25.1.tar.xz
shell(#<Th:0x007febed8a48b0>): /usr/local//brew//bin/xzcat emacs-25.1.tar.xz
shell(#<Th:0x007febed8a48b0>): /usr/bin/bzip2

Does the script requires brew to be installed? Am i using it in the wrong way?

regards.

**Comment by caldwell** [comment]
I think these are Ruby version issues. If you're on PowerPC you're probably on an older OS with Ruby 1.8. In my environment I actually run the fetch program from an up-to-date Debian Linux (since xz isn't supported by macOS tar). That's why it converts from xz to bzip2 at the end (which is supported by macOS tar).

I bet if you change
```
IO.popen(["curl", "-s", url]) do |io|
```
to
```
IO.popen("curl -s #{url}") do |io|
```

It'll work.

**Comment by pfmc** [comment]
Hi,

Thank you for the suppport :).
I am in OSX 10.5.8 which has ruby 1.8.
I have tested the change but know i get another error:

./fetch-emacs-from-ftp:51:in `<main>': undefined method `[]' for  
nil:NilClass (NoMethodError)

I have also installed ruby2.4.1 from macports, and reverting to  
original line code i get this same error.

What i have tried to do is:

./fetch-emacs-from-ftp -v ftp://ftp.gnu.org/pub/gnu/emacs/emacs-25.2.tar.xz

Should i use the full statement from the example:

$ ./fetch-emacs-from-ftp -v ftp://ftp.gnu.org/pub/gnu/emacs
+ curl --continue-at - --silent -O ftp://ftp.gnu.org/pub/gnu/emacs/emacs-25.1.tar.xz
shell(#<Th:0x007febed8a48b0>): /usr/local//brew//bin/xzcat  
emacs-25.1.tar.xz
shell(#<Th:0x007febed8a48b0>): /usr/bin/bzip2

And regarding the  brew part "/usr/local//brew//bin/xzcat", is it  
required to have homebrew installed?

Regards.

**Comment by pfmc** [comment]
This is line 51 in the clone i have:

base = latest[:file].sub(/\.xz|\.gz|\.bz2/, "")

**Comment by pfmc** [comment]
Sorry for the brew thing. i seem to have all the progs, as long as there are no paths defined strictly as in the example i guess.

**Comment by caldwell** [comment]
So that `shell(#<Th:0x007febed8a48b0>): /usr/local//brew//bin/xzcat` output is not an error but an annoying message from Ruby's "Shell" library. You can ignore it (it's just printing the commands it's running). It looks like that worked (it prints nothing on success).

I just remembered I use this binary Ruby on 10.6 (not sure about 10.5.8):
https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.leopard_64.bottle.tar.gz

But it sounds like you have that covered now with MacPorts.
