### ISSUE TITLE
[26.2] url-retrieve-synchronously returns empty with some https URLs

### ISSUE THREAD

**Issue by twlz0ne** [caldwell/build-emacs#78]
Here is my test (all binaries downloaded from https://emacsformacosx.com/emacs-builds/):

```org
#+BEGIN_SRC sh :results output :async
elisp="\
(with-current-buffer
    (url-retrieve-synchronously
     \"https://codeload.github.com/emacs-china/org-mode/zip/release_9.1.5\")
  (princ (format \"[%s.%s] buffer-size: %s\n\" emacs-major-version emacs-minor-version (buffer-size))))"

/Applications/Emacs-25.2.app/Contents/MacOS/Emacs       --batch --eval "$elisp"
/Applications/Emacs-25.3.1.app/Contents/MacOS/Emacs     --batch --eval "$elisp"
/Applications/Emacs-26.1.app/Contents/MacOS/Emacs       --batch --eval "$elisp"
/Applications/Emacs-26.2.app/Contents/MacOS/Emacs       --batch --eval "$elisp"
/Applications/Emacs-Nightly.app/Contents/MacOS/Emacs    --batch --eval "$elisp"
#+END_SRC

#+RESULTS:
: [25.2] buffer-size: 2757877
: [25.3] buffer-size: 2757877
: [26.1] buffer-size: 2757877
: [26.2] buffer-size: 0
: [27.0] buffer-size: 2757877
```

Then I built Emacs 26.2 from source (https://emacsformacosx.com/emacs-sources/emacs-26.2.tar.xz) on Linux and macOS.

- On Linux, the issue disappeared
- On macOS, the issue still exists while enabling `gnutls`

I think there should be a **new binary** of Emacs 26.2 **without gnutls**.

**Comment by caldwell** [comment]
Compiling without gnutls isn't really an option: Too many sites are TLS-only nowadays and the trend is only moving closer to 100%. But it sounds like there's a bug here somewhere. The nightly and the 26.2 should be built with the same version of gnutls (they share a Jenkins repo), so I suspect this might be a bug in Emacs itself. The best thing to do is to use `M-x report-emacs-bug` which will report the bug to the Emacs maintainers. They might be able to help narrow it down more (there should be more error reporting somewhere).
In the meantime I'm closing this because I don't believe it's a build-script bug. If the evidence comes back that it _is_, feel free to reopen the bug.
